FROM nginx:alpine

ARG DOCKERIZE_VERSION=v0.0.4

ADD https://github.com/jwilder/dockerize/releases/download/${DOCKERIZE_VERSION}/dockerize-linux-amd64-v0.0.4.tar.gz /tmp
RUN tar -xvzf /tmp/dockerize-linux-amd64-v0.0.4.tar.gz -C /usr/local/bin && \
    rm /tmp/dockerize-linux-amd64-${DOCKERIZE_VERSION}.tar.gz

COPY nginx.sh cw.tmpl /

ENTRYPOINT ["/nginx.sh"]